import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { getFeedbackByShareToken } from "@/lib/data/interview.data";
import { cn } from "@/lib/utils";

// A share link is "unlisted", not public: anyone holding the token may read it,
// but it must never end up in a search index. Without this, a single link
// posted anywhere would make the report permanently discoverable — and revoking
// the token would not remove it from search results.
export const metadata: Metadata = {
  robots: { index: false, follow: false, nocache: true },
};

// Public, read-only candidate report. Reachable only via an unguessable
// owner-minted token; revoking the token 404s this page.
const Page = async ({ params }: RouteParams) => {
  const { token } = await params;
  const shared = await getFeedbackByShareToken(token);

  if (!shared) {
    return (
      <div className="mx-auto max-w-xl px-6 py-24 text-center flex flex-col gap-4">
        <h2>Report not found</h2>
        <p className="text-light-400">
          This share link is invalid or has been revoked by its owner.
        </p>
        <Link href="/" className="text-primary-100 font-semibold">
          Go to PrepWise →
        </Link>
      </div>
    );
  }

  const { feedback, interview } = shared;

  const scoreColor = (score: number) => {
    if (score >= 80) return "text-success-100";
    if (score >= 60) return "text-yellow-400";
    return "text-destructive-100";
  };

  return (
    <div className="mx-auto max-w-3xl px-6 py-12 flex flex-col gap-8">
      <div className="flex flex-col gap-2 text-center">
        <p className="text-xs uppercase tracking-widest text-light-400">
          Shared interview report · PrepWise
        </p>
        <h2 className="capitalize">
          {interview ? `${interview.role} Interview` : "Interview"} — Candidate
          Report
        </h2>
        <p>
          Overall score:{" "}
          <span className={cn("font-bold text-lg", scoreColor(feedback.totalScore))}>
            {feedback.totalScore}/100
          </span>
        </p>
      </div>

      <section className="flex flex-col gap-4">
        <h3>Breakdown by Category</h3>
        {feedback.categoryScores.map(({ name, score, comment }) => (
          <div key={name} className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <p className="font-semibold">{name}</p>
              <p className={cn("font-bold", scoreColor(score))}>{score}/100</p>
            </div>
            <div className="w-full bg-dark-300 rounded-full h-2">
              <div
                className={cn(
                  "h-2 rounded-full",
                  score >= 80
                    ? "bg-success-100"
                    : score >= 60
                    ? "bg-yellow-400"
                    : "bg-destructive-100"
                )}
                style={{ width: `${score}%` }}
              />
            </div>
            <p className="text-light-400 text-sm">{comment}</p>
          </div>
        ))}
      </section>

      <section className="flex flex-col gap-3">
        <h3>Strengths</h3>
        <ul className="flex flex-col gap-2">
          {feedback.strengths.map((s, i) => (
            <li key={i} className="flex gap-2 items-start">
              <span className="text-success-100 mt-1">✓</span>
              <p>{s}</p>
            </li>
          ))}
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h3>Areas for Improvement</h3>
        <ul className="flex flex-col gap-2">
          {feedback.areasForImprovement.map((a, i) => (
            <li key={i} className="flex gap-2 items-start">
              <span className="text-destructive-100 mt-1">→</span>
              <p>{a}</p>
            </li>
          ))}
        </ul>
      </section>

      <section className="flex flex-col gap-2">
        <h3>Final Assessment</h3>
        <p className="text-light-400">{feedback.finalAssessment}</p>
      </section>

      <p className="text-center text-xs text-light-400">
        Generated by{" "}
        <Link href="/" className="text-primary-100">
          PrepWise
        </Link>{" "}
        — AI interview practice with adaptive voice interviews.
      </p>
    </div>
  );
};

export default Page;
